### ISSUE TITLE
求助，为何我引入报错了呢？

### ISSUE THREAD

**Issue by ameibj** [SeakeyCode/vue-kityminder-editor#3]
![image](https://user-images.githubusercontent.com/16263441/68441987-bb170d00-020a-11ea-8584-8ce9ab22ed3c.png)
![image](https://user-images.githubusercontent.com/16263441/68442021-ccf8b000-020a-11ea-94bd-b7c08d8503e0.png)

**Comment by SeakeyCode** [comment]
已经重构，请重新安装
